/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Entidades.*;
import Factory.Factory;
import Procesos.*;
import GUI.*;
import java.util.ArrayList;

/**
 *
 * @author carlo
 */
public class ComentariosGUI extends javax.swing.JFrame {

    static int ID;
    private static Factory factory;
    
    /**
     * Creates new form Vistarestaurant
     */
    public ComentariosGUI(int ID_restaurante) {
        factory = new Factory();
        initComponents();
        this.ID = ID_restaurante;
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel2 = new java.awt.Panel();
        panel_comentario = new javax.swing.JPanel();
        lbl_dejaComentario = new javax.swing.JLabel();
        btn_enviar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtBox_comentarios = new javax.swing.JTextArea();
        txt_nombre = new javax.swing.JTextField();
        lbl_calificacion = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        lbl_cliente1 = new javax.swing.JLabel();
        cbox_calificacion = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtBox_comentario = new javax.swing.JTextArea();
        panel_informacion = new java.awt.Panel();
        lbl_restaurante = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbl_tipoComida = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lbl_direccion = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_telefono = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_horario = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        lbl_propietario = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        lbl_coordenadas = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtBox_direccion = new javax.swing.JTextArea();
        lbl_clasificacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_tituloComentarios = new javax.swing.JLabel();

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Comentarios");
        setBackground(new java.awt.Color(0, 51, 204));
        setForeground(new java.awt.Color(0, 51, 153));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                apertura(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_comentario.setBackground(new java.awt.Color(33, 150, 243));
        panel_comentario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_dejaComentario.setBackground(new java.awt.Color(255, 255, 255));
        lbl_dejaComentario.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        lbl_dejaComentario.setForeground(new java.awt.Color(240, 240, 240));
        lbl_dejaComentario.setText("Deja un comentario");
        panel_comentario.add(lbl_dejaComentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        btn_enviar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        btn_enviar.setText("Enviar comentario");
        btn_enviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_enviarActionPerformed(evt);
            }
        });
        panel_comentario.add(btn_enviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 680, -1, -1));

        txtBox_comentarios.setEditable(false);
        txtBox_comentarios.setColumns(20);
        txtBox_comentarios.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtBox_comentarios.setLineWrap(true);
        txtBox_comentarios.setRows(5);
        txtBox_comentarios.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtBox_comentarios);

        panel_comentario.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 720, 440));

        txt_nombre.setBackground(new java.awt.Color(33, 150, 243));
        txt_nombre.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(255, 255, 255));
        txt_nombre.setBorder(null);
        txt_nombre.setOpaque(false);
        panel_comentario.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 530, 340, -1));

        lbl_calificacion.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_calificacion.setForeground(new java.awt.Color(255, 255, 255));
        lbl_calificacion.setText("Calificacion:");
        panel_comentario.add(lbl_calificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 530, -1, -1));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        panel_comentario.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 425, 12));

        lbl_cliente1.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_cliente1.setForeground(new java.awt.Color(255, 255, 255));
        lbl_cliente1.setText("Cliente:");
        panel_comentario.add(lbl_cliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        cbox_calificacion.setBackground(new java.awt.Color(33, 150, 243));
        cbox_calificacion.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        cbox_calificacion.setForeground(new java.awt.Color(255, 255, 255));
        cbox_calificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        panel_comentario.add(cbox_calificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 530, 160, -1));

        txtBox_comentario.setColumns(20);
        txtBox_comentario.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtBox_comentario.setRows(5);
        txtBox_comentario.setWrapStyleWord(true);
        jScrollPane3.setViewportView(txtBox_comentario);

        panel_comentario.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 720, -1));

        getContentPane().add(panel_comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 760, 730));

        panel_informacion.setBackground(new java.awt.Color(255, 255, 255));
        panel_informacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_restaurante.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbl_restaurante.setText("Restaurante: ");
        panel_informacion.add(lbl_restaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        lbl_nombre.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_nombre.setText("Nombre:");
        panel_informacion.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panel_informacion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 425, 12));

        lbl_tipoComida.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_tipoComida.setText("Tipo de Comida: ");
        panel_informacion.add(lbl_tipoComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panel_informacion.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 425, 12));

        lbl_direccion.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_direccion.setText("Direccion:");
        panel_informacion.add(lbl_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panel_informacion.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 425, 12));

        lbl_telefono.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_telefono.setText("Telefono:");
        panel_informacion.add(lbl_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panel_informacion.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 425, 12));

        lbl_horario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_horario.setText("Horarios:");
        panel_informacion.add(lbl_horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        panel_informacion.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 425, 12));

        lbl_propietario.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_propietario.setText("Propietario:");
        panel_informacion.add(lbl_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        panel_informacion.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 425, 12));

        lbl_coordenadas.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        lbl_coordenadas.setText("Coordenadas:");
        panel_informacion.add(lbl_coordenadas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 660, -1, -1));

        jSeparator7.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        panel_informacion.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 425, 12));

        txtBox_direccion.setEditable(false);
        txtBox_direccion.setColumns(20);
        txtBox_direccion.setFont(new java.awt.Font("Roboto", 0, 20)); // NOI18N
        txtBox_direccion.setLineWrap(true);
        txtBox_direccion.setRows(5);
        txtBox_direccion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtBox_direccion);

        panel_informacion.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 296, 420, 120));

        lbl_clasificacion.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        lbl_clasificacion.setText("Clasificacion: 0.0");
        panel_informacion.add(lbl_clasificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        getContentPane().add(panel_informacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 470, 730));

        jPanel1.setBackground(new java.awt.Color(25, 118, 210));

        lbl_tituloComentarios.setBackground(new java.awt.Color(255, 255, 255));
        lbl_tituloComentarios.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        lbl_tituloComentarios.setForeground(new java.awt.Color(255, 255, 255));
        lbl_tituloComentarios.setText("Ultimos comentarios");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lbl_tituloComentarios)
                .addContainerGap(861, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_tituloComentarios)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1230, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apertura(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_apertura
        BaseDatos base = factory.baseDatos();
        Restaurante restaurantes = base.restauranteByID(ID);
        
        int id = restaurantes.getId();
        String nombre = restaurantes.getNombre();
        String tipoComida = restaurantes.getTipoComida();
        String direccion = restaurantes.getDireccion();
        int telefono = restaurantes.getTelefono(); 
        String horarios = restaurantes.getHorarios();
        String propietarios = restaurantes.getPropietarios();
        String coordenadas = restaurantes.getCoordenadas();
        Double clasificacion = restaurantes.getClasificacion();  
        
        this.lbl_nombre.setText("Nombre: "+nombre);
        this.lbl_tipoComida.setText("Tipo de Comida: "+tipoComida);
        this.txtBox_direccion.setText("Dirección: "+direccion);
        this.lbl_telefono.setText("Telefono: "+String.valueOf(telefono));
        this.lbl_horario.setText("Horarios: "+horarios);
        this.lbl_propietario.setText("Propietarios: "+propietarios);
        this.lbl_coordenadas.setText("Coordenadas: "+coordenadas);
        this.lbl_clasificacion.setText("Clasificacion: "+String.valueOf(clasificacion));
        
        this.rellenarComentarios();
    }//GEN-LAST:event_apertura

    private void rellenarComentarios(){
        BaseDatos base = factory.baseDatos();
        ArrayList<Comentario> listaComentarios = base.obtenerComentarios(ID);
        int numeroComentarios = listaComentarios.size();
        
        this.txtBox_comentarios.setText("");
        
        for(int i =0;i<numeroComentarios;i++){
            Comentario comentario = listaComentarios.get(i);
            
            int id_restaurante = comentario.getId_restaurante();
            String usuario = comentario.getUsuario();
            String comentario2 = comentario.getComentario();
            int calificacion = comentario.getCalificacion();
            
            this.txtBox_comentarios.setText(this.txtBox_comentarios.getText() + usuario+": "+ comentario2 + "\nCalificacion: " +calificacion +"\n\n");
        }
    }
    
    private void btn_enviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_enviarActionPerformed
        BaseDatos base = factory.baseDatos();
        
        int id_restaurante = ID;
        String usuario = this.txt_nombre.getText();
        String comentario = this.txtBox_comentario.getText();
        int calificacion = Integer.parseInt(this.cbox_calificacion.getItemAt(this.cbox_calificacion.getSelectedIndex()));
        
        boolean exitoso = false;
        exitoso = base.insertarComentario(id_restaurante, usuario, comentario, calificacion);
        
        if(exitoso==true){
            this.rellenarComentarios();
            this.txtBox_comentario.setText("");
            this.txt_nombre.setText("");
        }else{
            System.out.print("Error al ingresar el comentario");
        }      
    }//GEN-LAST:event_btn_enviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComentariosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComentariosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComentariosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComentariosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComentariosGUI(ID).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_enviar;
    private javax.swing.JComboBox<String> cbox_calificacion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JLabel lbl_calificacion;
    private javax.swing.JLabel lbl_clasificacion;
    private javax.swing.JLabel lbl_cliente1;
    private javax.swing.JLabel lbl_coordenadas;
    private javax.swing.JLabel lbl_dejaComentario;
    private javax.swing.JLabel lbl_direccion;
    private javax.swing.JLabel lbl_horario;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_propietario;
    private javax.swing.JLabel lbl_restaurante;
    private javax.swing.JLabel lbl_telefono;
    private javax.swing.JLabel lbl_tipoComida;
    private javax.swing.JLabel lbl_tituloComentarios;
    private java.awt.Panel panel2;
    private javax.swing.JPanel panel_comentario;
    private java.awt.Panel panel_informacion;
    private javax.swing.JTextArea txtBox_comentario;
    private javax.swing.JTextArea txtBox_comentarios;
    private javax.swing.JTextArea txtBox_direccion;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
