/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import Entidades.*;
import Factory.Factory;
import Procesos.*;
import GUI.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author carlo
 */
public class Principal extends javax.swing.JFrame {
    private static Factory factory;
    /**
     * Creates new form Principal
     */
    public Principal() {
        factory = new Factory();
        initComponents();
        cargarColumnasTabla();
        cargarModeloTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        lbl_titulo = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_busqueda = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_restaurantes = new javax.swing.JTable();
        btn_comentario = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guia de Restaurantes");

        panel1.setBackground(new java.awt.Color(250, 250, 250));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_titulo.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        lbl_titulo.setText("Guia de Restaurantes");
        panel1.add(lbl_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btn_buscar.setText("Buscar por nombre");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });
        panel1.add(btn_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 230, -1, -1));

        jScrollPane1.setViewportView(txt_busqueda);

        panel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 200, -1));

        tabla_restaurantes.setModel(modeloTabla);
        jScrollPane2.setViewportView(tabla_restaurantes);

        panel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 1120, 270));

        btn_comentario.setText("Dejar un comentario");
        btn_comentario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_comentarioActionPerformed(evt);
            }
        });
        panel1.add(btn_comentario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 213, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/9.png"))); // NOI18N
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, -30, 270, 320));
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cold_drink_20594.png"))); // NOI18N
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/pizza_food_20620 (1).png"))); // NOI18N
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/meat_food_20586.png"))); // NOI18N
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 540, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/chicken_food_20625.png"))); // NOI18N
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cattle_kitchen_food_20596.png"))); // NOI18N
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 540, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1161, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    DefaultTableModel modeloTabla = new DefaultTableModel();
    
    private void cargarColumnasTabla(){
        
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Tipo de Comida");
        modeloTabla.addColumn("Direccion");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("Horarios");
        modeloTabla.addColumn("Propiedades");
        modeloTabla.addColumn("Coordenadas");
        modeloTabla.addColumn("Clasificacion");
  
    }
    
    private void cargarModeloTabla(){
        BaseDatos base = factory.baseDatos();
        ArrayList<Restaurante> listaRestaurantes = base.obtenerRestaurantes();
        
        int numRestaurantes = listaRestaurantes.size();
        modeloTabla.setNumRows(numRestaurantes);
        
        for(int i =0;i<numRestaurantes;i++){
            Restaurante restaurantes = listaRestaurantes.get(i);
                    
            int id = restaurantes.getId();
            String nombre = restaurantes.getNombre();
            String tipoComida = restaurantes.getTipoComida();
            String direccion = restaurantes.getDireccion();
            int telefono = restaurantes.getTelefono(); 
            String horarios = restaurantes.getHorarios();
            String propietarios = restaurantes.getPropietarios();
            String coordenadas = restaurantes.getCoordenadas();
            Double clasificacion = restaurantes.getClasificacion();  
            
            modeloTabla.setValueAt(id, i, 0);
            modeloTabla.setValueAt(nombre, i, 1);
            modeloTabla.setValueAt(tipoComida, i, 2);
            modeloTabla.setValueAt(direccion, i, 3);
            modeloTabla.setValueAt(telefono, i, 4);
            modeloTabla.setValueAt(horarios, i, 5);
            modeloTabla.setValueAt(propietarios, i, 6);
            modeloTabla.setValueAt(coordenadas, i, 7);
            modeloTabla.setValueAt(clasificacion, i, 8);
            
        }
    }
    
    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        BaseDatos base = factory.baseDatos();
        String busqueda = this.txt_busqueda.getText();
        ArrayList<Restaurante> listaRestaurantes = base.obtenerRestaurantesBYName(busqueda);
        
        int numRestaurantes = listaRestaurantes.size();
        modeloTabla.setNumRows(numRestaurantes);
        
        for(int i =0;i<numRestaurantes;i++){
            Restaurante restaurantes = listaRestaurantes.get(i);
                    
            int id = restaurantes.getId();
            String nombre = restaurantes.getNombre();
            String tipoComida = restaurantes.getTipoComida();
            String direccion = restaurantes.getDireccion();
            int telefono = restaurantes.getTelefono(); 
            String horarios = restaurantes.getHorarios();
            String propietarios = restaurantes.getPropietarios();
            String coordenadas = restaurantes.getCoordenadas();
            Double clasificacion = restaurantes.getClasificacion();  
            
            modeloTabla.setValueAt(id, i, 0);
            modeloTabla.setValueAt(nombre, i, 1);
            modeloTabla.setValueAt(tipoComida, i, 2);
            modeloTabla.setValueAt(direccion, i, 3);
            modeloTabla.setValueAt(telefono, i, 4);
            modeloTabla.setValueAt(horarios, i, 5);
            modeloTabla.setValueAt(propietarios, i, 6);
            modeloTabla.setValueAt(coordenadas, i, 7);
            modeloTabla.setValueAt(clasificacion, i, 8);
            
        }
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_comentarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_comentarioActionPerformed
        int columna = 0;
        int row = tabla_restaurantes.getSelectedRow();
        String valorS = tabla_restaurantes.getModel().getValueAt(row, columna).toString();
        int valorInt = Integer.parseInt(valorS);
        
        ComentariosGUI comentarios = factory.comentariosForm(valorInt);
        comentarios.setVisible(true);
        
    }//GEN-LAST:event_btn_comentarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_comentario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_titulo;
    private java.awt.Panel panel1;
    private javax.swing.JTable tabla_restaurantes;
    private javax.swing.JTextPane txt_busqueda;
    // End of variables declaration//GEN-END:variables
}
